version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2001:2001"  
    networks:
      - app-network
    depends_on:
      - db  

  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin@1234  
      MYSQL_DATABASE: yeahnotework  
      MYSQL_USER: root  
      MYSQL_PASSWORD: admin@1234  
    ports:
      - "3307:3306"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
